#!/bin/bash

IP=${IP:='127.0.0.1'}
PACKAGE_PREFIX=${PACKAGE_PREFIX:='/usr/local/val-verde-platform-sdk-gnu-haswell/sysroot/usr/bin'}
PORT=${PORT:='7777'}
SITE_DIR=${SITE_DIR:='${HOME}/site'}
SOURCE_ROOT=${SOURCE_ROOT:='./'}
STAGE_ROOT=${STAGE_ROOT:='./'}

sed "s|SITE_DIR|${SITE_DIR}|g; \
     s|PORT|${PORT}|g; \
     s|IP|${IP}|g; \
     s|PACKAGE_PREFIX|${PACKAGE_PREFIX}|g" \
     ${SOURCE_ROOT}/baikonur.service.in > ${STAGE_ROOT}/baikonur.service
